<?php
return [
    '/billing/tariff/<type:\d+>' => '/billing/tariff/index',
    '/billing/tariff/view/<id:\d+>' => '/billing/tariff/view',
    '/billing/client/view/<id:\d+>' => '/billing/client/view',
    '/billing/payment/view/<id:\w+>' => '/billing/payment/view',
    '/billing/tariff/update/<id:\d+>' => '/billing/tariff/update',
    '/billing/tariff/delete/<id:\d+>' => '/billing/tariff/delete',

    '/crm/lead/update/<id:\d+>' => '/crm/lead/update',
    '/crm/lead/delete/<id:\d+>' => '/crm/lead/delete',
    '/crm/deal/update/<id:\d+>' => '/crm/deal/update',
    '/crm/deal/delete/<id:\d+>' => '/crm/deal/delete',
    '/crm/company/update/<id:\d+>' => '/crm/company/update',
    '/crm/company/delete/<id:\d+>' => '/crm/company/delete',
    '/crm/contact/update/<id:\d+>' => '/crm/contact/update',
    '/crm/contact/delete/<id:\d+>' => '/crm/contact/delete',
    '/crm/product/update/<id:\d+>' => '/crm/product/update',
    '/crm/product/delete/<id:\d+>' => '/crm/product/delete',
    '/billing/ip-addresses/update/<id:\d+>' => '/billing/ip-addresses/update',
    '/billing/ip-addresses/delete/<id:\d+>' => '/billing/ip-addresses/delete',
    '/billing/services/update/<id:\d+>' => '/billing/services/update',
    '/billing/services/delete/<id:\d+>' => '/billing/services/delete',
    '/billing/share/update/<id:\d+>' => '/billing/share/update',
    '/billing/share/delete/<id:\d+>' => '/billing/share/delete',
    '/billing/tv-channel/update/<id:\d+>' => '/billing/tv-channel/update',
    '/billing/tv-channel/delete/<id:\d+>' => '/billing/tv-channel/delete',
    '/billing/tv-packet/update/<id:\d+>' => '/billing/tv-packet/update',
    '/billing/tv-packet/delete/<id:\d+>' => '/billing/tv-packet/delete',
    '/billing/internet/update/<id:\d+>' => '/billing/internet/update',
    '/billing/internet/delete/<id:\d+>' => '/billing/internet/delete',
    '/crm/company-type/update/<id:\d+>' => '/crm/company-type/update',
    '/crm/company-type/delete/<id:\d+>' => '/crm/company-type/delete',
    '/crm/company-scope/update/<id:\d+>' => '/crm/company-scope/update',
    '/crm/company-scope/delete/<id:\d+>' => '/crm/company-scope/delete',
    '/crm/currency/update/<id:\d+>' => '/crm/currency/update',
    '/crm/currency/delete/<id:\d+>' => '/crm/currency/delete',
    '/billing/units/update/<id:\d+>' => '/billing/units/update',
    '/billing/units/delete/<id:\d+>' => '/billing/units/delete',
    '/crm/deal-type/update/<id:\d+>' => '/crm/deal-type/update',
    '/crm/deal-type/delete/<id:\d+>' => '/crm/deal-type/delete',
    '/crm/crm-status/update/<id:\d+>' => '/crm/crm-status/update',
    '/crm/crm-status/delete/<id:\d+>' => '/crm/crm-status/delete',
    '/billing/channel-broadcast-language/update/<id:\d+>' => '/billing/channel-broadcast-language/update',
    '/billing/channel-broadcast-language/delete/<id:\d+>' => '/billing/channel-broadcast-language/delete',
    '/billing/channel-quality/update/<id:\d+>' => '/billing/channel-quality/update',
    '/billing/channel-quality/delete/<id:\d+>' => '/billing/channel-quality/delete',
    '/billing/channel-category/update/<id:\d+>' => '/billing/channel-category/update',
    '/billing/channel-category/delete/<id:\d+>' => '/billing/channel-category/delete',

    '/hr/default/read/<model:\w+>' => '/hr/default/read',
    '/hr/default/create/<model:\w+>' => '/hr/default/create',
    '/hr/default/upload/<userId:\d+>' => '/hr/default/upload',
];