<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'NOTE: When editing an existing record, both the {category} name and its settings will be modified.' => 'ՆՇՈՒՄ. Գոյություն ունեցող գրառումը խմբագրելիս և՛ {category} անունը, և՛ դրա կարգավորումները կփոփոխվեն:',
    'NOTE: When editing an existing record, only the {category} name will be modified (and not the settings).' => 'ՆՇՈՒՄ. Գոյություն ունեցող գրառումը խմբագրելիս կփոխվի միայն {category} անունը (և ոչ թե կարգավորումները)',
    'Abort any changes and reset settings' => 'Դադարեցնել ցանկացած փոփոխություն և վերականգնել կարգավորումները',
    'Apply' => 'Պահպանել',
    'Are you sure you want to delete the setting?' => 'Վստա՞հ եք, որ ցանկանում եք ջնջել կարգավորումը:',
    'Configure Order and Display of Grid Columns' => 'Կարգավորեք աղյուսակի սյունների կարգը և ցուցադրումը',
    'Default Filter' => 'Հիմնական ֆիլտր',
    'Default Sort' => 'Հիմնական տեսակավորում',
    'Delete' => 'Ջնջել',
    'Filter Configuration' => '',
    'Filter Name' => 'Ֆիլտրի անունը',
    'Grid Theme' => 'Աղյուսակի տեսք',
    'Hidden / Fixed Columns' => 'Թաքնված / ֆիքսված սյունակներ',
    'Integer between {min} to {max}' => 'Թիվը {min}-ից մինչև {max}',
    'Operation disallowed! Invalid request signature detected for dynagrid settings. {params}' => '',
    'Page Size' => 'Էջերի քանակ',
    'Personalize Grid Configuration' => 'Անհատականացրեք աղյուսակի պարամետրերը',
    'Personalize grid settings' => 'Անհատականացնել աղյուսակի կարգավորումները',
    'Remove saved grid settings' => 'Հեռացնել պահպանված աղյուսակի պարամետրերը',
    'Reset' => 'Թարմացնել',
    'Save' => 'Պահպանել',
    'Save / Edit Grid {title}' => 'Պահել / Խմբագրել աղյուսակի {title}ը',
    'Save / edit grid {category}' => 'Պահել / խմբագրել աղյուսակի {category}ը',
    'Save grid settings' => 'Պահպանել աղյուսակի կաչգավորումները',
    'Saved Filters' => 'Պահպանված ֆիլտրեր',
    'Saved Sorts' => 'Պահպանված տեսակավորումներ',
    'Saving and applying configuration' => 'Կարգավորումների պահպանում և կիրառում',
    'Select a filter...' => 'Ընտրել ֆիլտր',
    'Select a sort...' => 'Ընտրել տեսակավորում',
    'Select a theme...' => 'Ընտրել տեսքը',
    'Select theme to style grid' => 'Ընտրեք թեման աղյուսակի տեսքի համար',
    'Select...' => 'Ընտրել',
    'Set a name to save the state of your current grid {category}. You can alternatively select a saved {category} from the list below to edit or delete.' => 'Նշեք անուն՝ ձեր աղյուսակի ներկայիս {category}ը պահպանելու համար: Ստորև ներկայացված ցուցակից այլընտրանքորեն կարող եք ընտրել պահված {category}՝ խմբագրելու կամ ջնջելու համար:',
    'Set default grid filter criteria' => 'Սահմանեք աղյուսակի ֆիլտրի հիմնական չափանիշները',
    'Set default grid sort criteria' => 'Սահմանեք աղյուսակի տեսակավորման հիմնական չափանիշները',
    'Sort Configuration' => 'Տեսակավորել կարգավորումը',
    'Sort Name' => 'Տեսակավորման անուն',
    'Trash' => 'Ջնջել կարգավորումները',
    'Trashing all personalizations' => 'Ջնջել բոլոր անհատականացումը',
    'Visible Columns' => 'Տեսանելի սյուններ',
    'ascending' => 'աճող',
    'descending' => 'նվազող',
    'filter' => 'ֆիլտր',
    'grid' => 'աղյուսակ',
    'rows per page' => 'տողեր մեկ էջի համար',
    'sort' => 'տեսակավորում',
];
